spring.application.name=auctiondemo
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db
spring.datasource.username=root
spring.datasource.password=Mohanraj@99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true